/*
 * This file is generated by jOOQ.
 */
package com.kdemo.jooq.domain;


import com.kdemo.jooq.domain.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.user</code>.
     */
    public static final User USER = com.kdemo.jooq.domain.tables.User.USER;
}
