/*
 * This file is generated by jOOQ.
*/
package com.kdemo.jooq.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = -1691746493;

    private Long   id;
    private String name;
    private String gender;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.name = value.name;
        this.gender = value.gender;
    }

    public Users(
        Long   id,
        String name,
        String gender
    ) {
        this.id = id;
        this.name = name;
        this.gender = gender;
    }

    @NotNull
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Size(max = 1)
    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(gender);

        sb.append(")");
        return sb.toString();
    }
}
