/*
 * This file is generated by jOOQ.
*/
package com.kdemo.jooq.domain.tables.daos;


import com.kdemo.jooq.domain.tables.Users;
import com.kdemo.jooq.domain.tables.records.UsersRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UsersDao extends DAOImpl<UsersRecord, com.kdemo.jooq.domain.tables.pojos.Users, Long> {

    /**
     * Create a new UsersDao without any configuration
     */
    public UsersDao() {
        super(Users.USERS, com.kdemo.jooq.domain.tables.pojos.Users.class);
    }

    /**
     * Create a new UsersDao with an attached configuration
     */
    @Autowired
    public UsersDao(Configuration configuration) {
        super(Users.USERS, com.kdemo.jooq.domain.tables.pojos.Users.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.kdemo.jooq.domain.tables.pojos.Users object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.kdemo.jooq.domain.tables.pojos.Users> fetchById(Long... values) {
        return fetch(Users.USERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.kdemo.jooq.domain.tables.pojos.Users fetchOneById(Long value) {
        return fetchOne(Users.USERS.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.kdemo.jooq.domain.tables.pojos.Users> fetchByName(String... values) {
        return fetch(Users.USERS.NAME, values);
    }

    /**
     * Fetch a unique record that has <code>name = value</code>
     */
    public com.kdemo.jooq.domain.tables.pojos.Users fetchOneByName(String value) {
        return fetchOne(Users.USERS.NAME, value);
    }

    /**
     * Fetch records that have <code>gender IN (values)</code>
     */
    public List<com.kdemo.jooq.domain.tables.pojos.Users> fetchByGender(String... values) {
        return fetch(Users.USERS.GENDER, values);
    }
}
